USE QLBongDa

--a: TRUY VAN CO BAN
--1.
SELECT MACT, HOTEN, VITRI, SO, NGAYSINH, DIACHI FROM dbo.CAUTHU

--2.
SELECT * FROM dbo.CAUTHU
WHERE dbo.CAUTHU.VITRI = N'Tiền vệ' AND	dbo.CAUTHU.SO = 7

--3.
SELECT TENHLV, NGAYSINH, DIACHI, DIENTHOAI FROM dbo.HUANLUYENVIEN

--4.
SELECT * FROM dbo.CAUTHU
WHERE dbo.CAUTHU.MAQG = 'VN' AND dbo.CAUTHU.MACLB = 'BBD'

--5.
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI FROM dbo.CAUTHU
WHERE dbo.CAUTHU.MACLB = 'SDN' AND dbo.CAUTHU.MAQG = 'BRA'

--6.
SELECT * FROM dbo.CAUTHU
INNER JOIN dbo.CAULACBO
ON (dbo.CAULACBO.MACLB = dbo.CAULACBO.MACLB) 
INNER JOIN dbo.SANVD
ON (dbo.SANVD.MASAN = dbo.CAULACBO.MASAN) AND (dbo.SANVD.TENSAN = N'Long An')

--7.
SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, TD.MACLB1, TD.MACLB2, TD.KETQUA FROM dbo.TRANDAU AS TD
INNER JOIN dbo.SANVD AS SVD
ON (SVD.MASAN = TD.MASAN) AND TD.NAM = 2009 AND TD.VONG = 2
INNER JOIN dbo.CAULACBO AS CLB1
ON CLB1.MACLB = TD.MACLB1
INNER JOIN dbo.CAULACBO AS CLB2
ON CLB2.MACLB = TD.MACLB2

--8.
SELECT HLV_CLB.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HLV_CLB.VAITRO, CLB.TENCLB FROM dbo.HUANLUYENVIEN AS HLV
INNER JOIN dbo.HLV_CLB AS HLV_CLB
ON HLV_CLB.MAHLV = HLV.MAHLV AND HLV.MAQG = 'VN'
INNER JOIN dbo.CAULACBO AS CLB
ON CLB.MACLB = HLV_CLB.MACLB

--9.
SELECT TENCLB FROM dbo.CAULACBO
INNER JOIN dbo.BANGXH AS XH
ON XH.MACLB = CAULACBO.MACLB AND XH.VONG = 3 AND XH.NAM = 2009 AND XH.HANG < 4
ORDER BY XH.DIEM DESC

--10.
SELECT HLV_CLB.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HLV_CLB.VAITRO, CLB.TENCLB FROM dbo.HUANLUYENVIEN AS HLV
INNER JOIN dbo.HLV_CLB AS HLV_CLB
ON HLV_CLB.MAHLV = HLV.MAHLV
INNER JOIN dbo.CAULACBO AS CLB
ON CLB.MACLB = HLV_CLB.MACLB AND CLB.MATINH = 'BD'

--B: CAC PHEP TOAN TREN NHOM
--1.
SELECT CAULACBO.TENCLB AS [Tên CLB], COUNT(dbo.CAUTHU.MACT) AS [Số lượng cầu thủ] FROM dbo.CAUTHU, dbo.CAULACBO
WHERE dbo.CAULACBO.MACLB = dbo.CAUTHU.MACLB
GROUP BY TENCLB

--2.
SELECT CLB.TENCLB AS [Tên CLB], COUNT(CT.MACT) AS [Số lượng cầu thủ nước ngoài] FROM dbo.CAUTHU AS CT, dbo.CAULACBO AS CLB
WHERE CLB.MACLB = CT.MACLB AND CT.MAQG <> 'VN'
GROUP BY CLB.TENCLB

--3.
SELECT CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI, COUNT(CT.MACT) AS [Số lượng cầu thủ nước ngoài] FROM dbo.CAULACBO AS CLB
INNER JOIN dbo.SANVD AS SVD
ON SVD.MASAN = CLB.MASAN	
INNER JOIN dbo.CAUTHU AS CT
ON CT.MACLB = CLB.MACLB AND CT.MAQG <> 'VN'
GROUP BY CLB.TENCLB, CLB.MACLB, SVD.TENSAN, SVD.DIACHI
HAVING COUNT(CT.MACT) > 2

--4.
SELECT TINH.TENTINH, COUNT(CT.MACT) AS [Số lượng cầu thủ] FROM dbo.CAUTHU AS CT, dbo.TINH AS TINH, dbo.CAULACBO AS CLB
WHERE CT.VITRI = N'Tiền đạo' AND CLB.MACLB = CT.MACLB AND CLB.MATINH = TINH.MATINH
GROUP BY TINH.TENTINH

--5.
SELECT CLB.TENCLB, TINH.TENTINH FROM dbo.CAULACBO AS CLB, dbo.TINH AS TINH, dbo.BANGXH AS BXH
WHERE TINH.MATINH = CLB.MATINH AND CLB.MACLB = BXH.MACLB AND BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = 1

--c: CAC TOAN TU NANG CAO
--1.
SELECT HLV.TENHLV FROM dbo.HLV_CLB AS HLV_CLB
INNER JOIN dbo.HUANLUYENVIEN AS HLV
ON HLV_CLB.MAHLV = HLV.MAHLV AND HLV.DIENTHOAI IS NULL

--2.
SELECT HLV.TENHLV FROM dbo.HUANLUYENVIEN AS HLV
INNER JOIN dbo.HLV_CLB AS HLV_CLB
ON (HLV.MAQG = 'VN') AND (HLV_CLB.MAHLV = HLV.MAHLV) AND (HLV_CLB.MACLB IS NULL)

--3.
SELECT dbo.CAUTHU.HOTEN FROM dbo.CAUTHU, dbo.BANGXH, dbo.CAULACBO
WHERE dbo.CAUTHU.MACLB = dbo.CAULACBO.MACLB  AND dbo.BANGXH.MACLB = dbo.CAULACBO.MACLB AND dbo.BANGXH.VONG = 3 AND dbo.BANGXH.NAM = 2009 AND dbo.BANGXH.HANG NOT BETWEEN 3 AND 6

--4.
DECLARE @maclb VARCHAR(5)
SELECT @maclb = dbo.CAULACBO.MACLB FROM dbo.CAULACBO, dbo.BANGXH
WHERE dbo.BANGXH.MACLB = dbo.CAULACBO.MACLB AND dbo.BANGXH.HANG = 1 AND dbo.BANGXH.NAM = 2009 AND dbo.BANGXH.VONG = 1

SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS [CLB1], CLB2.TENCLB AS [CLB2], TD.KETQUA FROM dbo.TRANDAU AS TD, dbo.CAULACBO AS CLB1, dbo.CAULACBO AS CLB2, dbo.SANVD AS SVD
WHERE SVD.MASAN = TD.MASAN AND TD.MACLB1 = CLB1.MACLB AND TD.MACLB2 = CLB2.MACLB AND TD.VONG BETWEEN 1 AND 3 AND (@maclb = TD.MACLB1 OR @maclb = TD.MACLB2) 