--Buoi 1 CO SO DU LIEU HUST--
--link: https://bk-csdl.github.io/
--1. Dowload Microsoft SQL Management Studio
--2. 
--Note: Khong the nhap lieu cho table co khoa ngoai truoc khi nhap lieu cho table co chua khoa chinh la no;
--"Khoa ngoai": la khoa chinh cua mot table khac;

--code:

-->New query: edit code:
CREATE DATABASE QLBongDa --create a database named "QLBongDa";

USE QLBongDa

CREATE TABLE CAUTHU --create tables for database;
(
	MACT NUMERIC NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	VITRI NVARCHAR(20) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MACLB VARCHAR(5) NOT NULL,
	MAQG VARCHAR(5) NOT NULL,
	SO INT NOT NULL

)

CREATE TABLE QUOCGIA
(
	MAQG VARCHAR(5) PRIMARY KEY,
	TENQG NVARCHAR(60) NOT NULL
)

CREATE TABLE CAULACBO
(
	MACLB VARCHAR(5) PRIMARY KEY,
	TENCLB NVARCHAR(100) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	MATINH VARCHAR(5) NOT NULL
)

CREATE TABLE TINH
(
	MATINH VARCHAR(5) PRIMARY KEY,
	TENTINH NVARCHAR(100) NOT NULL
)

CREATE TABLE SANVD
(
	MASAN VARCHAR(5) PRIMARY KEY,
	TENSAN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200)
)

CREATE TABLE HUANLUYENVIEN
(
	MAHLV VARCHAR(5) PRIMARY KEY,
	TENHLV NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL
)

CREATE TABLE HLV_CLB
(
	MAHLV VARCHAR(5),
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100) NOT NULL,
	PRIMARY KEY(MAHLV, MACLB)
)

CREATE TABLE TRANDAU
(
	MATRAN NUMERIC IDENTITY(1, 1) PRIMARY KEY,
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	NGAYTD DATETIME NOT NULL,
	MACLB1 VARCHAR(5) NOT NULL,
	MACLB2 VARCHAR(5) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	KETQUA VARCHAR(5) NOT NULL
)

CREATE TABLE BANGXH
(
	MACLB VARCHAR(5),
	NAM INT,
	VONG INT,
	SOTRAN INT NOT NULL,
	THANG INT NOT NULL,
	HOA INT NOT NULL,
	THUA INT NOT NULL,
	HIEUSO VARCHAR(5) NOT NULL,
	DIEM INT NOT NULL,
	HANG INT NOT NULL,
	PRIMARY KEY(MACLB, NAM, VONG)
)
--add foreign key, primary key;
ALTER TABLE dbo.CAUTHU ADD FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)
ALTER TABLE	dbo.CAUTHU ADD FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)
ALTER TABLE dbo.CAULACBO ADD FOREIGN KEY(MATINH) REFERENCES dbo.TINH(MATINH)
ALTER TABLE dbo.CAULACBO ADD FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN)
ALTER TABLE dbo.HUANLUYENVIEN ADD FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)
ALTER TABLE dbo.HLV_CLB ADD	FOREIGN KEY(MAHLV) REFERENCES dbo.HUANLUYENVIEN(MAHLV)
ALTER TABLE dbo.HLV_CLB ADD FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)
ALTER TABLE dbo.TRANDAU ADD	FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN)
ALTER TABLE dbo.TRANDAU ADD FOREIGN KEY(MACLB1) REFERENCES dbo.CAULACBO(MACLB)
ALTER TABLE dbo.TRANDAU ADD FOREIGN KEY(MACLB2) REFERENCES dbo.CAULACBO(MACLB)
ALTER TABLE dbo.BANGXH ADD FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)


